export const fonts = {
  black: 'RobotoCondensed-Black',
  blackItalic: 'RobotoCondensed-BlackItalic',
  bold: 'RobotoCondensed-Bold',
  boldItalic: 'RobotoCondensed-BoldItalic',
  extraBold: 'RobotoCondensed-ExtraBold',
  extraBoldItalic: 'RobotoCondensed-ExtraBoldItalic',
  extraLight: 'RobotoCondensed-ExtraLight',
  extraLightItalic: 'RobotoCondensed-ExtraLightItalic',
  italic: 'RobotoCondensed-Italic',
  light: 'RobotoCondensed-Light',
  lightItalic: 'RobotoCondensed-LightItalic',
  medium: 'RobotoCondensed-Medium',
  mediumItalic: 'RobotoCondensed-MediumItalic',
  regular: 'RobotoCondensed-Regular',
  semiBold: 'RobotoCondensed-SemiBold',
  semiBoldItalic: 'RobotoCondensed-SemiBoldItalic',
  thin: 'RobotoCondensed-Thin',
  thinItalic: 'RobotoCondensed-ThinItalic',
};
